spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 529440
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true